# Generated by Django 2.2.12 on 2020-06-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'RUR')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'PrivatBank'), (2, 'MonoBank'),
                                                            (3, 'Vkurse'), (4, 'ObmennikUa'), (5, 'Alfabank'),
                         (6, 'Taskombank')]),
        ),
    ]
